### ISSUE TITLE
how to reproduce the paper?

### ISSUE THREAD

**Issue by initializer-z** [Wang-Yu-Qing/UTPM#1]
When I run `main.py`, I only get results hundreds of times less than the the metric `prec@K` in the paper. Maybe I should change the default params? Could you know how to reproduce the performance in the paper?

epoch: 017 | current_step: 06500 | current_batch_loss: 0.2886 | epoch_avg_loss: 0.1810 | step_time: 0.02418                                                       [657/1903]
epoch: 017 | current_step: 07000 | current_batch_loss: 0.0690 | epoch_avg_loss: 0.1811 | step_time: 0.02362
epoch: 017 | current_step: 07500 | current_batch_loss: 0.1576 | epoch_avg_loss: 0.1808 | step_time: 0.02478
epoch: 017 | current_step: 08000 | current_batch_loss: 0.1787 | epoch_avg_loss: 0.1809 | step_time: 0.03756
epoch: 017 | current_step: 08500 | current_batch_loss: 0.2345 | epoch_avg_loss: 0.1808 | step_time: 0.02088
epoch: 017 | current_step: 09000 | current_batch_loss: 0.0598 | epoch_avg_loss: 0.1808 | step_time: 0.02079
epoch: 017 | current_step: 09500 | current_batch_loss: 0.0499 | epoch_avg_loss: 0.1809 | step_time: 0.02824
epoch: 017 | current_step: 10000 | current_batch_loss: 0.2452 | epoch_avg_loss: 0.1812 | step_time: 0.02112
epoch: 017 | current_step: 10500 | current_batch_loss: 0.1587 | epoch_avg_loss: 0.1808 | step_time: 0.02448
epoch: 017 | current_step: 11000 | current_batch_loss: 0.1648 | epoch_avg_loss: 0.1807 | step_time: 0.03396
epoch: 017 | current_step: 11500 | current_batch_loss: 0.1808 | epoch_avg_loss: 0.1808 | step_time: 0.02634
epoch: 017 | current_step: 12000 | current_batch_loss: 0.0701 | epoch_avg_loss: 0.1808 | step_time: 0.02398
epoch: 017 | current_step: 12500 | current_batch_loss: 0.0939 | epoch_avg_loss: 0.1808 | step_time: 0.02277
epoch: 017 | current_step: 13000 | current_batch_loss: 0.0962 | epoch_avg_loss: 0.1806 | step_time: 0.02471
Epoch 17 done, epoch avg loss: 0.18072199821472168
Early stop
Save model weights to saved_model.pickle
Load model weights from saved_model.pickle
precision@1: 0.001058548693239889
precision@2: 0.001058548693239889
precision@3: 0.00166691001119385

**Comment by Wang-Yu-Qing** [comment]
This project is still under developing, I met the same issue that can't reproduce the paper. Need some time to find out why.

**Comment by Wang-Yu-Qing** [comment]
@initializer-z There are some improvements in the code. But still cannot reach the performance described in the paper. You can checkout the lastes metrics.

**Comment by Wang-Yu-Qing** [comment]
I think the paper's data preprocess method (e.g. filter out some long-tail user / movie) is different with mine and this is crutial to the evaluation result. But we cannot find these details in the paper. So the gap still exists.
