### ISSUE TITLE
询问下大佬几个疑问

### ISSUE THREAD

**Issue by yunchenran** [Wang-Yu-Qing/UTPM#2]
1. 我看代码里貌似没有对 padding 的部分做 mask softmax，不知道是不是我看漏了呢？
 2. 看论文里貌似对双头的注意力输出还是 E，但代码里貌似是拼起来处理的，这里我其实也有疑问，因为按照 Transformer 里的多头的话，最终输出的 attention embedding 是切分成 num_head 份，所以最终不论几个头最后输出维度都是一致的，这里是否也需要做这种处理呢（比如先把序列的 embedding 也先切成 num_head份）？

<img width="477" alt="image" src="https://user-images.githubusercontent.com/5258460/154488177-df291d24-bb26-494c-9d42-be50bec1c623.png">

**Comment by Wang-Yu-Qing** [comment]
第一个问题：
  在模型部分的训练代码里使用reset_pad_embedding函数，在每次向前传播时，padding value的embedding为0，向后传播之后，又会再次将padding value的embedding强制设置为0。训练的样本是二分类的正负样本，我理解这样应该不用mask softmax了。
第二个问题：
  可以看下论文里的figure2，图里attention fusion layer的两个输出A，输入交叉层后看着是拼接在一起的。如果想要保持原来的维度，也可以做sum pooling或者max pooling，这些都是融合手段，除了维度过高影响后续交叉的性能外，我感觉实际影响不大。
