### ISSUE TITLE
求教两个问题

### ISSUE THREAD

**Issue by lemonadeseason** [Wang-Yu-Qing/UTPM#3]
你好，最近在看这篇论文，感谢开源复现代码，有两个问题想求教一下：
（1）不同feature field之间attention的weight与bias好像并没有定义：https://github.com/Wang-Yu-Qing/UTPM/blob/master/model.py#L122   直接使用了最后一轮循环的w与b，这样是不是不合理呢？
（2）https://github.com/Wang-Yu-Qing/UTPM/blob/59922d05ea8f1988d6f2eaf1b71546ae5e3b7be6/utils.py#L168   没太看懂这个user_frac有什么用，有一部分用户评分行为完全没有被drop掉是出于什么原因呢？请问原文里有提到这个操作嘛？
期待回复 : ）

**Comment by lemonadeseason** [comment]
另外代码里cross feature似乎只用了二阶交叉，没有linear的部分？

**Comment by Wang-Yu-Qing** [comment]
第一个问题：我看了下确实有误，近期抽空做下修改，感谢提醒！
第二个问题：user_frac是为了缩减数据规模，在实验阶段快速跑通demo，详见README中**Run the model**部分
第三个问题：代码里确实少了一个交叉层对输入向量的l2 norm的部分，这部分输出和交叉向量拼接后，将作为交叉层的最后输出送入全连接层。

**Comment by lemonadeseason** [comment]
> 第一个问题：我看了下确实有误，近期抽空做下修改，感谢提醒！ 第二个问题：user_frac是为了缩减数据规模，在实验阶段快速跑通demo，详见README中**Run the model**部分 第三个问题：代码里确实少了一个交叉层对输入向量的l2 norm的部分，这部分输出和交叉向量拼接后，将作为交叉层的最后输出送入全连接层。

谢谢回复~

**Comment by lemonadeseason** [comment]
你好，我可能又发现了一个问题：https://github.com/Wang-Yu-Qing/UTPM/blob/59922d05ea8f1988d6f2eaf1b71546ae5e3b7be6/utils.py#L283   
future里的user tag没有固定个数吗？这样的话有的电影tag多有的则少，数量不一致可以放在同一个batch里嘛？

**Comment by Wang-Yu-Qing** [comment]
@lemonadeseason tag的数量有固定，不足的话会padding，超过的话会cut，参见`pad_or_cut`函数。之前提的问题最新的代码应该修复了，可以看一下。

**Comment by lemonadeseason** [comment]
@Wang-Yu-Qing   谢谢回复
https://github.com/Wang-Yu-Qing/UTPM/blob/master/utils.py#L271
271和272行只对history（用来构建用户画像的那部分数据）的tag和category进行了pad_or_cut，好像对future（将来的训练集/测试集）的tag并没有进行pad_or_cut?

**Comment by Wang-Yu-Qing** [comment]
@lemonadeseason Future是作为label的，这部分tags在损失函数（论文公式4）中，同用户向量做点积、累加，然后sigmoid，不需要做padding。

**Comment by lemonadeseason** [comment]
@Wang-Yu-Qing 是的，论文里并没有说future的tag要固定数量。但我在用torch实现的过程中，torch要求同一batch里每一条数据的tag数量一致，不知道TensorFlow是不是可以不一样

**Comment by Wang-Yu-Qing** [comment]
@lemonadeseason 我看了下，label的tag数量确实固定了，具体在由`tags_per_movie`控制，在提取电影-标签关系时做了限制。
