### ISSUE TITLE
self.reset_pad_embedding()

### ISSUE THREAD

**Issue by Aliang-CN** [Wang-Yu-Qing/UTPM#5]
大佬，这个函数有什么作用呢？ self.reset_pad_embedding()

**Comment by Wang-Yu-Qing** [comment]
因为tf没法支持带padding值的embedding lookup，所以我这里手动实现了一下。reset_pad_embedding是将所有padding值重新设为0，防止向后传播后，padding值也进行了梯度更新，导致其值不为0。
