### ISSUE TITLE
Train slowly

### ISSUE THREAD

**Issue by linWujl** [Wang-Yu-Qing/UTPM#6]
It seems the GPU-Util is very low, althought increase the batch size.
BTW, may be the block of step time should be placed after apply_gradients function ?

**Comment by Wang-Yu-Qing** [comment]
Yes, the time count should be placed after `apply_gradients`. Did you set `use_cross` to `True`? If so, the speed will be slow because it performs feature cross for all features. And this process cannot be optimized (as far as I known) like FM feature crossing part.

**Comment by linWujl** [comment]
I didn't set use_cross to True. The gpu-util is always about 3-5%. 
Have you ever met this problem?

> Yes, the time count should be placed after `apply_gradients`. Did you set `use_cross` to `True`? If so, the speed will be slow because it performs feature cross for all features. And this process cannot be optimized (as far as I known) like FM feature crossing part.

**Comment by Wang-Yu-Qing** [comment]
If your GPU memory is vacant, **try to increase the batch_size** to fully utilize the GPU ability.
