### ISSUE TITLE
特征相关问题

### ISSUE THREAD

**Issue by mingmin95** [Wang-Yu-Qing/UTPM#7]
想请教一下作者，为啥UTPM只使用categorical feature或者sequence feature，为啥不用numerical features呢，是使用过效果不好，还是numerical features性能等因素所以不用

**Comment by Wang-Yu-Qing** [comment]
hi，我并不是论文作者哈，只是复现了下论文。一般复现论文时主要关注模型相关的编码工作，从而简化了特征工程相关的部分。使用连续型变量也是可以的，不过对于推荐算法领域中常用的基于embedding的深度神经网络而言，一般都是输入离散化之后的特征值。如果想使用连续型特征，一般是先做离散化，这里也有很多种方法例如等频分桶、等距分桶以及一些其他方法（例如YoutubeDNN论文中的数值编码方法）。
