### ISSUE TITLE
Cant write to pickle file

### ISSUE THREAD

**Issue by mosaad2707** [Wang-Yu-Qing/UTPM#9]
Traceback (most recent call last):
  File "/Users/saad/UTPM/main.py", line 60, in <module>
    save(model, 'model.pickle')
  File "/Users/saad/UTPM/utils.py", line 376, in save
    f.write(pickle.dumps(obj))
            ^^^^^^^^^^^^^^^^^
AttributeError: Can't pickle local object 'BaseOptimizer.__init__.<locals>.<lambda>'

**Comment by Wang-Yu-Qing** [comment]
This is a version issue, switch to another save method like https://stackoverflow.com/questions/77476322/attributeerror-cant-pickle-local-object-how-to-fix-this-issue

**Comment by mosaad2707** [comment]
Since UTMP is being defined as a custom class , it'll have to be redefined and changes to model.py will have to be made ?

**Comment by mosaad2707** [comment]
using earlier versions of Tensorflow worked as a better option
